import type { Metadata } from "next";
import { Alex_Brush, EB_Garamond, Alegreya } from "next/font/google";
import "./globals.css";

const alexBrush = Alex_Brush({
  variable: "--font-alex-brush",
  weight: "400",
  subsets: ["latin"],
});

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const alegreya = Alegreya({
  variable: "--font-alegreya",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alexBrush.variable} ${ebGaramond.variable} ${alegreya.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
